services:
  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gur8_network

  redis:
    image: redis:latest
    networks:
      - gur8_network

  web:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    command: gunicorn gur8.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - gur8_network

  worker:
    build:
      context: .
      dockerfile: docker/celery/Dockerfile
    command: celery -A gur8 worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis
    networks:
      - gur8_network

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - gur8_network

volumes:
  postgres_data:

networks:
  gur8_network:
    driver: bridge